package nt.evn.com.entities;

// Generated Apr 18, 2015 2:54:07 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "evn_reward")
public class Department implements java.io.Serializable {
    private static final long serialVersionUID = 4129141062214699764L;
    private String            dmntId;
    private String            dmntNme;
    private String            dmntDcspt;

    public Department() {}

    public Department(String dmntId) {
        this.dmntId = dmntId;
    }

    public Department(String dmntId, String dmntNme, String dmntDcspt) {
        this.dmntId = dmntId;
        this.dmntNme = dmntNme;
        this.dmntDcspt = dmntDcspt;
    }

    @Id
    @Column(name = "dmnt_id", unique = true, nullable = false, length = 15)
    public String getDmntId() {
        return this.dmntId;
    }

    public void setDmntId(String dmntId) {
        this.dmntId = dmntId;
    }

    @Column(name = "dmnt_nme", length = 300)
    public String getDmntNme() {
        return this.dmntNme;
    }

    public void setDmntNme(String dmntNme) {
        this.dmntNme = dmntNme;
    }

    @Column(name = "dmnt_dcspt", length = 500)
    public String getDmntDcspt() {
        return this.dmntDcspt;
    }

    public void setDmntDcspt(String dmntDcspt) {
        this.dmntDcspt = dmntDcspt;
    }

}
