package nt.evn.com.entities;

// Generated Apr 19, 2015 3:54:43 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reward generated by hbm2java
 */
@Entity
@Table(name = "reward", catalog = "evn_reward")
public class Reward implements java.io.Serializable {

    private static final long serialVersionUID = -8395977919887984702L;
    private Integer           rwdId;
    private RewardFile        rewardFile;
    private byte              rwdType;
    private Date              rwdDte;
    private int               subjectId;
    private BigDecimal        rwdVal;
    private String            rwdDcrpt;

    public Reward() {}

    public Reward(byte rwdType, int subjectId, String rwdDcrpt) {
        this.rwdType = rwdType;
        this.subjectId = subjectId;
        this.rwdDcrpt = rwdDcrpt;
    }

    public Reward(RewardFile rewardFile, byte rwdType, Date rwdDte, int subjectId,
            BigDecimal rwdVal, String rwdDcrpt) {
        this.rewardFile = rewardFile;
        this.rwdType = rwdType;
        this.rwdDte = rwdDte;
        this.subjectId = subjectId;
        this.rwdVal = rwdVal;
        this.rwdDcrpt = rwdDcrpt;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "rwd_id", unique = true, nullable = false)
    public Integer getRwdId() {
        return this.rwdId;
    }

    public void setRwdId(Integer rwdId) {
        this.rwdId = rwdId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rwd_file_id")
    public RewardFile getRewardFile() {
        return this.rewardFile;
    }

    public void setRewardFile(RewardFile rewardFile) {
        this.rewardFile = rewardFile;
    }

    @Column(name = "rwd_type", nullable = false)
    public byte getRwdType() {
        return this.rwdType;
    }

    public void setRwdType(byte rwdType) {
        this.rwdType = rwdType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "rwd_dte", length = 10)
    public Date getRwdDte() {
        return this.rwdDte;
    }

    public void setRwdDte(Date rwdDte) {
        this.rwdDte = rwdDte;
    }

    @Column(name = "subject_id", nullable = false)
    public int getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }

    @Column(name = "rwd_val", precision = 20, scale = 0)
    public BigDecimal getRwdVal() {
        return this.rwdVal;
    }

    public void setRwdVal(BigDecimal rwdVal) {
        this.rwdVal = rwdVal;
    }

    @Column(name = "rwd_dcrpt", nullable = false, length = 500)
    public String getRwdDcrpt() {
        return this.rwdDcrpt;
    }

    public void setRwdDcrpt(String rwdDcrpt) {
        this.rwdDcrpt = rwdDcrpt;
    }

}
