package nt.evn.com.entities;

// Generated Apr 19, 2015 3:54:43 PM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RewardFile generated by hbm2java
 */
@Entity
@Table(name = "reward_file", catalog = "evn_reward")
public class RewardFile implements java.io.Serializable {

    private static final long serialVersionUID = 1337950182302535482L;
    private int               rwdFileId;
    private String            rwdFileName;
    private String            rwdFileType;
    private byte[]            rwdFileData;
    private Set<Reward>       rewards          = new HashSet<Reward>(0);

    public RewardFile() {}

    public RewardFile(int rwdFileId, String rwdFileName) {
        this.rwdFileId = rwdFileId;
        this.rwdFileName = rwdFileName;
    }

    public RewardFile(int rwdFileId, String rwdFileName, String rwdFileType, byte[] rwdFileData,
            Set<Reward> rewards) {
        this.rwdFileId = rwdFileId;
        this.rwdFileName = rwdFileName;
        this.rwdFileType = rwdFileType;
        this.rwdFileData = rwdFileData;
        this.rewards = rewards;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "rwd_file_id", unique = true, nullable = false)
    public int getRwdFileId() {
        return this.rwdFileId;
    }

    public void setRwdFileId(int rwdFileId) {
        this.rwdFileId = rwdFileId;
    }

    @Column(name = "rwd_file_name", nullable = false, length = 250)
    public String getRwdFileName() {
        return this.rwdFileName;
    }

    public void setRwdFileName(String rwdFileName) {
        this.rwdFileName = rwdFileName;
    }

    @Column(name = "rwd_file_type", length = 150)
    public String getRwdFileType() {
        return this.rwdFileType;
    }

    public void setRwdFileType(String rwdFileType) {
        this.rwdFileType = rwdFileType;
    }

    @Column(name = "rwd_file_data")
    public byte[] getRwdFileData() {
        return this.rwdFileData;
    }

    public void setRwdFileData(byte[] rwdFileData) {
        this.rwdFileData = rwdFileData;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rewardFile")
    public Set<Reward> getRewards() {
        return this.rewards;
    }

    public void setRewards(Set<Reward> rewards) {
        this.rewards = rewards;
    }

}
